export const store = {
   
    dogs:[{
       "name":"Molly",
       "sex":"female",
       "breed":"briard",
       "img":"https://images.dog.ceo/breeds/briard/n02105251_6840.jpg",
       "present":false,
       "age":4,
       "chipNumber":"IEH455006",
       "owner":{
          "name":"Wilmer",
          "lastName":"Svensson",
          "phoneNumber":"0769239356"
       }
    },
    {
       "name":"Bella",
       "sex":"female",
       "breed":"labrador",
       "img":"https://images.dog.ceo/breeds/labrador/n02099712_3947.jpg",
       "present":false,
       "age":1,
       "chipNumber":"HPF367168",
       "owner":{
          "name":"Tina",
          "lastName":"Ahlberg",
          "phoneNumber":"0732303484"
       }
    },
    {
       "name":"Charlie",
       "sex":"male",
       "breed":"retriever",
       "img":"https://images.dog.ceo/breeds/retriever-chesapeake/n02099849_3645.jpg",
       "present":true,
       "age":5,
       "chipNumber":"DBP669806",
       "owner":{
          "name":"Tina",
          "lastName":"Hök",
          "phoneNumber":"0708671977"
       }
    },
    {
       "name":"Ludde",
       "sex":"male",
       "breed":"greyhound",
       "img":"https://images.dog.ceo/breeds/greyhound-italian/n02091032_907.jpg",
       "present":true,
       "age":5,
       "chipNumber":"HLM936015",
       "owner":{
          "name":"David",
          "lastName":"Emraz",
          "phoneNumber":"0762592136"
       }
    },
    {
       "name":"Doris",
       "sex":"female",
       "breed":"groenendael",
       "img":"https://images.dog.ceo/breeds/groenendael/n02105056_2194.jpg",
       "present":true,
       "age":8,
       "chipNumber":"ELN562847",
       "owner":{
          "name":"David",
          "lastName":"Ahlberg",
          "phoneNumber":"0765237613"
       }
    },
    {
       "name":"Sigge",
       "sex":"male",
       "breed":"husky",
       "img":"https://images.dog.ceo/breeds/husky/n02110185_8860.jpg",
       "present":false,
       "age":7,
       "chipNumber":"HAA378909",
       "owner":{
          "name":"Moa",
          "lastName":"Jonsson",
          "phoneNumber":"0705896593"
       }
    },
    {
       "name":"Wilma",
       "sex":"female",
       "breed":"akita",
       "img":"https://images.dog.ceo/breeds/akita/Akita_inu_blanc.jpg",
       "present":false,
       "age":6,
       "chipNumber":"GEL894256",
       "owner":{
          "name":"David",
          "lastName":"Doner",
          "phoneNumber":"0705449389"
       }
    },
    {
       "name":"Bamse",
       "sex":"male",
       "breed":"newfoundland",
       "img":"https://images.dog.ceo/breeds/newfoundland/n02111277_6402.jpg",
       "present":false,
       "age":6,
       "chipNumber":"FAK548352",
       "owner":{
          "name":"Lollo",
          "lastName":"Emraz",
          "phoneNumber":"0762550965"
       }
    },
    {
       "name":"Sally",
       "sex":"female",
       "breed":"schnauzer",
       "img":"https://images.dog.ceo/breeds/schnauzer-miniature/n02097047_157.jpg",
       "present":false,
       "age":2,
       "chipNumber":"JLO423741",
       "owner":{
          "name":"Emma",
          "lastName":"Kihl",
          "phoneNumber":"0703474026"
       }
    },
    {
       "name":"Alice",
       "sex":"female",
       "breed":"border collie",
       "img":"https://images.dog.ceo/breeds/collie-border/n02106166_930.jpg",
       "present":true,
       "age":7,
       "chipNumber":"CFL247788",
       "owner":{
          "name":"Tina",
          "lastName":"Doner",
          "phoneNumber":"0762187564"
       }
    }
]
}
